# Generated by Django 4.1.7 on 2023-03-02 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('separator', models.CharField(choices=[(',', 'Comma(,)'), (' ', 'Space( )'), (';', 'Semicolon(;)')], default=';', max_length=1, verbose_name='Разделитель')),
                ('string_character', models.CharField(choices=[("'", "Quote(')"), ('"', 'Double-quote(")')], default='"', max_length=1, verbose_name='Строковый символ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Схема',
                'verbose_name_plural': 'Схемы',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('Full name', 'Full name'), ('Job', 'Job'), ('Email', 'Email'), ('Domain name', 'Domain name'), ('Phone number', 'Phone number'), ('Company name', 'Company name'), ('Text', 'Text'), ('Integer', 'Integer'), ('Address', 'Address'), ('Date', 'Date')], max_length=100, verbose_name='Тип')),
                ('from_num', models.IntegerField(blank=True, null=True, verbose_name='От')),
                ('to_num', models.IntegerField(blank=True, null=True, verbose_name='До')),
                ('schema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_csv.schema', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Колонка',
                'verbose_name_plural': 'Колонки',
                'unique_together': {('order', 'schema_id')},
            },
        ),
    ]
