# Generated by Django 4.1.7 on 2023-03-03 13:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fake_csv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='from_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='from'),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='column',
            name='schema_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_csv.schema'),
        ),
        migrations.AlterField(
            model_name='column',
            name='to_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('Full name', 'Full name'), ('Job', 'Job'), ('Email', 'Email'), ('Domain name', 'Domain name'), ('Phone number', 'Phone number'), ('Company name', 'Company name'), ('Text', 'Text'), ('Integer', 'Integer'), ('Address', 'Address'), ('Date', 'Date')], max_length=100),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schema',
            name='separator',
            field=models.CharField(choices=[(',', 'Comma(,)'), (' ', 'Space( )'), (';', 'Semicolon(;)')], default=';', max_length=1, verbose_name='Column separator'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[("'", "Quote(')"), ('"', 'Double-quote(")')], default='"', max_length=1),
        ),
        migrations.AlterField(
            model_name='schema',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('Processing', 'Processing')], max_length=20)),
                ('file', models.FileField(upload_to='csv_files')),
                ('rows', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('schema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_csv.schema')),
            ],
        ),
    ]
